In [ ]:
import numpy as np
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error 

In [ ]:
data=pd.read_csv("Boston.csv")

In [ ]:
data.head()

crim    zn  indus    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18  0.458  7.147  54.2  6.0622    3  222     18.7   

    black  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [ ]:
x=data.iloc[:,:12].values #value conversion saves times but not necessary 

In [ ]:
y=data.iloc[:,12].values

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)   #array unpacking
x_train,x_test,y_train,y_test

(array([[3.5809e-01, 0.0000e+00, 6.2000e+00, ..., 1.7400e+01, 3.9170e+02,
         9.7100e+00],
        [1.5876e-01, 0.0000e+00, 1.0810e+01, ..., 1.9200e+01, 3.7694e+02,
         9.8800e+00],
        [1.1329e-01, 3.0000e+01, 4.9300e+00, ..., 1.6600e+01, 3.9125e+02,
         1.1380e+01],
        ...,
        [1.5098e-01, 0.0000e+00, 1.0010e+01, ..., 1.7800e+01, 3.9451e+02,
         1.0300e+01],
        [2.2927e-01, 0.0000e+00, 6.9100e+00, ..., 1.7900e+01, 3.9274e+02,
         1.8800e+01],
        [1.3914e-01, 0.0000e+00, 4.0500e+00, ..., 1.6600e+01, 3.9690e+02,
         1.4690e+01]]),
 array([[6.7240e-02, 0.0000e+00, 3.2400e+00, ..., 1.6900e+01, 3.7521e+02,
         7.3400e+00],
        [9.2323e+00, 0.0000e+00, 1.8100e+01, ..., 2.0200e+01, 3.6615e+02,
         9.5300e+00],
        [1.1425e-01, 0.0000e+00, 1.3890e+01, ..., 1.6400e+01, 3.9374e+02,
         1.0500e+01],
        ...,
        [1.4932e-01, 2.5000e+01, 5.1300e+00, ..., 1.9700e+01, 3.9511e+02,
         1.3150e+01],
        [1.4

In [ ]:
model=LinearRegression() #object of the class

In [ ]:
model.fit(x_train,y_train)

LinearRegression()

In [ ]:
model.coef_  #beta values for each feature

array([-1.25156811e-01,  4.48575121e-02,  2.01265385e-02, -1.62895522e+01,
        3.77366409e+00, -2.13185120e-03, -1.40611846e+00,  2.66835482e-01,
       -1.21692284e-02, -1.07660161e+00,  8.72533635e-03, -4.94425348e-01])

In [ ]:
model.intercept_ # betanote value

38.42706211257675

In [ ]:
model.score(x_train,y_train)*100 #estimated model parameters /R squard value

76.90953567794605

In [ ]:
y_pred=model.predict(x_test) #to find the predictions (y values of x) of test data

In [ ]:
MSE=mean_squared_error(y_pred,y_test) 
MSE 

34.21225254753332

In [ ]:
RMSE=np.sqrt(MSE)
RMSE

5.849124083786676

In [ ]:
x_test.shape

(102, 12)

In [ ]:
 x2=np.array([0.00732,16.0,2.31,0.598,8.575,65.2,4.0800,1,236,17.3,396.90,4.98])
 x2

array([7.320e-03, 1.600e+01, 2.310e+00, 5.980e-01, 8.575e+00, 6.520e+01,
       4.080e+00, 1.000e+00, 2.360e+02, 1.730e+01, 3.969e+02, 4.980e+00])

In [ ]:
model.predict(x2.reshape(1,12))

array([35.70295324])